### ISSUE TITLE
Endpoint /user-personal nie znajduje użytkownika

### ISSUE THREAD

**Issue by wnekus** [ASKU-PI/asku-magazine-service#37]
Jak poniżej :thinking: pomimo, że rekord znajduje się w bazie
![Screenshot from 2021-10-31 09-44-06](https://user-images.githubusercontent.com/70373402/139575029-0acf12dc-103f-4da9-8893-061ac98d3dce.png)
![Screenshot from 2021-10-31 09-45-43](https://user-images.githubusercontent.com/70373402/139575033-1d721424-c97e-490d-a1ab-a5ab48a96c90.png)
![Screenshot from 2021-10-31 09-45-54](https://user-images.githubusercontent.com/70373402/139575034-1ad0d7d0-67e3-4a14-abbd-91b706984836.png)

**Comment by wnekus** [comment]
![Screenshot from 2021-10-31 09-51-06](https://user-images.githubusercontent.com/70373402/139575105-3e791cdb-437c-4897-8f0d-6297d67c62c0.png)
To też powinno chyba coś zwróić :thinking:

**Comment by sswrk** [comment]
@wnekus user znajduje się w bazie auth service czy zarówno auth-service i magazine-service?

**Comment by wnekus** [comment]
Problem lokalny. Resolved!
