### ISSUE TITLE
/daily-reservations /daily-states bug

### ISSUE THREAD

**Issue by wnekus** [ASKU-PI/asku-magazine-service#38]
Bad request na /daily-reservations pomimo porawnego requesta i tokenu (może chodzi o to body) :thinking: 
![Screenshot from 2021-10-31 10-22-28](https://user-images.githubusercontent.com/70373402/139576129-ab9f4247-b57e-4334-af34-14a96e31cd0c.png)
![Screenshot from 2021-10-31 10-23-07](https://user-images.githubusercontent.com/70373402/139576130-c62746cc-8e13-437d-aa9b-4abea10683fa.png)
![Screenshot from 2021-10-31 10-23-25](https://user-images.githubusercontent.com/70373402/139576131-be19b5eb-bdb0-422f-a671-2d207b3e2619.png)

**Comment by wnekus** [comment]
![Screenshot from 2021-10-31 10-23-58](https://user-images.githubusercontent.com/70373402/139576167-23319b6b-7df9-4141-b1bd-6a98aa81ac5f.png)
![Screenshot from 2021-10-31 10-24-10](https://user-images.githubusercontent.com/70373402/139576169-b82673d0-0b6b-4b95-806e-3a76eae356c3.png)

**Comment by wnekus** [comment]
To samo z /daily-states

**Comment by wnekus** [comment]
![Uploading Screenshot from 2021-10-31 10-41-19.png…]()

**Comment by sswrk** [comment]
@wnekus hmm masz wszystko zaktualizowane? U mnie jest tak:
![image](https://user-images.githubusercontent.com/58403334/139578702-1756c793-1dfb-4ebf-871e-a5a155744560.png)

**Comment by wnekus** [comment]
Resolved :hankey:
