### ISSUE TITLE
Nulle zamiast id rezerwacji

### ISSUE THREAD

**Issue by wnekus** [ASKU-PI/asku-magazine-service#40]
Zamiast id rezerwacji przychodzą nulle :disappointed: 
![Screenshot from 2021-10-31 13-14-25](https://user-images.githubusercontent.com/70373402/139582760-99f8433b-1bc3-4816-b977-1fea230b721a.png)

**Comment by sswrk** [comment]
Zapomniałem dać id do dto w converterze.

Naprawione i zmergowane
