### ISSUE TITLE
Nieprawidłowe stan dnia

### ISSUE THREAD

**Issue by wnekus** [ASKU-PI/asku-magazine-service#41]
Zwracany jest stan "SOME" mimo tego że nie ma rezerwacji na dany dzień. 
![Screenshot from 2021-11-01 09-50-52](https://user-images.githubusercontent.com/70373402/139649553-e31a9f42-ee46-43cf-bce5-a5140dd14fa6.png)
![Screenshot from 2021-11-01 09-51-15](https://user-images.githubusercontent.com/70373402/139649557-2a859c57-7b42-4564-a63f-411a24a4d394.png)
![Screenshot from 2021-11-01 09-51-49](https://user-images.githubusercontent.com/70373402/139649559-fd887fc9-e8e0-41d7-8512-22970cd6a4d6.png)
![Screenshot from 2021-11-01 09-55-00](https://user-images.githubusercontent.com/70373402/139649562-6af89379-38a0-4ccd-b9f9-76a2bd9e7f7d.png)

**Comment by sswrk** [comment]
done
