### ISSUE TITLE
Ilość zwracanych reviews

### ISSUE THREAD

**Issue by wnekus** [ASKU-PI/asku-magazine-service#46]
Czy możemy zwracać 4 reviewsy na stronę? Nie potrzebujemy w sumie 10, skoro nie są renderowane w danym momencie :thinking:

**Comment by sswrk** [comment]
Oczywiście, kwestia zmiany wartości jednej zmiennej

**Comment by wnekus** [comment]
:1st_place_medal:

**Comment by sswrk** [comment]
done
