### ISSUE TITLE
Bug - dodawanie review

### ISSUE THREAD

**Issue by wnekus** [ASKU-PI/asku-magazine-service#50]
![Screenshot from 2021-11-06 20-22-57](https://user-images.githubusercontent.com/70373402/140621441-b8f33e89-5e4b-4c63-ba06-cc9782c9e3b3.png)
![Screenshot from 2021-11-06 20-23-09](https://user-images.githubusercontent.com/70373402/140621442-877cc2cc-8349-4b33-961a-e18d356cfdb2.png)

**Comment by sswrk** [comment]
@wnekus Hmm reservationId powinno być jako request param a body to reviewDto

**Comment by wnekus** [comment]
Potestuje już jutro 😴 💤

**Comment by wnekus** [comment]
up, dalej to samo :disappointed: 
![Screenshot from 2021-11-07 09-51-08](https://user-images.githubusercontent.com/70373402/140638558-78f5c1cf-8713-4c11-947d-c7f4e153c18a.png)
![Screenshot from 2021-11-07 09-51-15](https://user-images.githubusercontent.com/70373402/140638561-d2b00f3c-8966-4e4e-a3b1-e700a5cfa241.png)

**Comment by wnekus** [comment]
Resolved!
