### ISSUE TITLE
Endpoint zawsze zwraca available 

### ISSUE THREAD

**Issue by wnekus** [ASKU-PI/asku-magazine-service#57]
Dla dni w których przestrzeń jest available zawsze zwracane jest true pomimo tego, że area jest zbyt duża :thinking: 
![Screenshot from 2021-11-08 18-25-52](https://user-images.githubusercontent.com/70373402/140789309-e8a674f6-ef97-4e49-b70b-b7da8833b083.png)
![Screenshot from 2021-11-08 18-24-51](https://user-images.githubusercontent.com/70373402/140789373-2fe44373-04f0-4bdb-8ed8-5bcaf81191a7.png)

**Comment by sswrk** [comment]
Eh, nie wziąłem pod uwagę przypadku gdy podana powierzchnia jest większa niż powierzchnia magazynu
Naprawione
