### ISSUE TITLE
Niepoprawna max area 

### ISSUE THREAD

**Issue by wnekus** [ASKU-PI/asku-magazine-service#58]
Jeśli przedział zawiera czas kiedy przestrzeń jest unvailable to endpoint powinien zwrócić 0 :bulb: 
![Screenshot from 2021-11-08 19-41-52](https://user-images.githubusercontent.com/70373402/140799282-7fc48c8e-a7a7-4eac-b87f-80ddcac2c9dd.png)

**Comment by sswrk** [comment]
done
