### ISSUE TITLE
Brak dostępnych metrów na jeden dzień

### ISSUE THREAD

**Issue by wnekus** [ASKU-PI/asku-magazine-service#60]
![Screenshot from 2021-11-08 20-37-25](https://user-images.githubusercontent.com/70373402/140806998-3e91fbf3-15c9-484b-accc-99069cb2cf54.png)
![Screenshot from 2021-11-08 20-36-58](https://user-images.githubusercontent.com/70373402/140807015-b19ee0f2-89cb-4ae0-8d2d-8c1848b478ec.png)

**Comment by sswrk** [comment]
> End date must be greater than end date

![image](https://user-images.githubusercontent.com/58403334/140828504-a0ef4fff-d3c3-41da-8ab7-8803eb98aa0f.png)

**Comment by sswrk** [comment]
done
