### ISSUE TITLE
Stany dla ilości rezerwacji

### ISSUE THREAD

**Issue by wnekus** [ASKU-PI/asku-magazine-service#66]
Fajnie byłoby mieć więcej stanów np unavailable, 0%, 1% - 33%, 34% - 66%, 67% - 100%.

**Comment by sswrk** [comment]
@wnekus może po prostu będę zwracał ile procent a Ty już sobie będziesz na froncie mapował zakres?

**Comment by wnekus** [comment]
> @wnekus może po prostu będę zwracał ile procent a Ty już sobie będziesz na froncie mapował zakres?

gitarka :+1:

**Comment by sswrk** [comment]
done - dodałem dodatkowe pole w dto z procentem zajętości
