### ISSUE TITLE
Endpoint /user-profile/id

### ISSUE THREAD

**Issue by wnekus** [ASKU-PI/asku-magazine-service#71]
Endpoint powinien być dostępny bez autoryzacji.

**Comment by sswrk** [comment]
done

**Comment by wnekus** [comment]
Nadal nie działa :disappointed: 
![Screenshot from 2021-11-16 23-27-58](https://user-images.githubusercontent.com/70373402/142076332-5fa133e3-8c2d-49bf-ab41-be3062a25341.png)

**Comment by wnekus** [comment]
Resolved.
