### ISSUE TITLE
State = zawsze 0%

### ISSUE THREAD

**Issue by wnekus** [ASKU-PI/asku-magazine-service#72]
Procent zarezerwowanej powierzchni to zawsze 0% lub 100%.

Odpowiednio:
* 20/222
* 150/222
* 222/222
* 111/222

![Screenshot from 2021-11-16 21-05-02](https://user-images.githubusercontent.com/70373402/142057719-ad8ebb84-e698-47c0-9ea7-074def028323.png)

**Comment by sswrk** [comment]
ehh, zapomniałem przez 100 pomnożyć

**Comment by wnekus** [comment]
> ehh, zapomniałem przez 100 pomnożyć

:heavy_plus_sign: :mage_man: :mage_man: :mage_man: :heavy_minus_sign:

**Comment by sswrk** [comment]
done
